shinyUI(
navbarPage(title="",
          windowTitle = "PSRC Equity Dashboard", 
          theme = "styles.css",

           tabPanel("Overview",
                    sidebarLayout(
                      sidebarPanel(id="sidebar",
                        div(img(src="psrc-logo.png", width = "100%", height = "100%", style = "padding-top: 5px")),
                        hr(),
                        h3("Equity Resources:"),
                        hr(),
                        tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/demographicprofile.pdf", "Central Puget Sound Demographic Profile", target="_blank"),
                        br(),
                        tags$a(class = "source_url", href="https://www.psrc.org/displacement-risk-mapping", "Displacement Risk Mapping", target="_blank"),
                        br(),
                        tags$a(class = "source_url", href="https://www.psrc.org/opportunity-mapping", "Opportunity Mapping", target="_blank"),
                        br(),
                        tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/rtp-appendixb-equityanalysis.pdf", "Regional Transportation Plan Equity Analysis", target="_blank"),
                        br(),
                        tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/vision2050equitypaper.pdf", "VISION 2050: Equity Briefing Paper", target="_blank"),
                        br(),
                        tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/v2050finalseis-appendixh-equity-march2020.pdf", "VISION 2050 Final SEIS Appendix H: Equity Analysis", target="_blank"),
                        hr(),
                        h4("Would you like more information?"),
                        hr(),
                        strong(tags$div(class="sidebar_notes","Charles Patton, Ph.D.")),
                        tags$a(class = "source_url", href="https://www.psrc.org/contact-center/have-question?contact=9626&destination=node/9362&width=75%25&height=75%25&subject=Planning%20for%20Equity", "Email", target="_blank"),
                        br(),
                        tags$div(class="sidebar_notes","206-971-3285"),
                        hr(),
                        width=3),
                      mainPanel(id="mainpanel",
                        h1("Planning for Equity"),
                        fluidRow(column(12,div(img(src="covid-mural.jpg", width = "75%", height = "75%", style = "padding-top: 25px")))
                        ),
                        br(),
                        h2("PSRC incorporates equity and social justice in its regional growth, transportation, and economic development planning."),
                        "The central Puget Sound region has a long history of racism that continues to cause enormous harm. Generations of discrimination, disinvestment, and inequitable opportunities have helped lay the groundwork for a region where people of color and white residents too often have completely different experiences.",
                        br(),br(),
                        "As a planning agency, PSRC makes decisions that shape transportation, land use, and the built environment. The agency has a responsibility to dismantle systems of inequity and reimagine a region where race can no longer predict life outcomes.",
                        br(),
                        h2("Regional Equity Strategy"),
                        "PSRC will develop a Regional Equity Strategy to improve outcomes for marginalized communities and how the agency operates internally. The agency will lead with race, which has proven to be an effective method for not only increasing equitable outcomes for people of color but developing a framework, tools, and resources that can remove barriers for other marginalized groups.",
                        br(),br(),
                        "The Regional Equity Strategy will provide guidance to help members work in a coordinated manner towards the region's goal of providing an exceptional quality of life and opportunity for all. It will also provide guidance and training for staff to ensure the agency effectively uses its roles to advance racial equity.",
                        br(),br(),
                        "The work plan is anticipated to be finalized in spring 2021, for the next budget and work program. Initial phases of the strategy will be finalized in 2022. This work will be ongoing.",
                        hr(),
                        div(img(src="equity-strategy-timeline.jpg", width = "100%", height = "100%", style = "padding-top: 5px")),
                      ) # End of Overview Panel
                    ) # End of Sidebar of Unemployment
           ),# End of Tab Panel of Overview Panel
           
          navbarMenu("Economic Data", 
            tabPanel("Median Income",
                     sidebarLayout(
                       sidebarPanel(id="sidebar",
                                    div(img(src="psrc-logo.png", width = "100%", height = "100%", style = "padding-top: 5px")),
                                    hr(),
                                    h3("Equity Resources:"),
                                    hr(),
                                    tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/demographicprofile.pdf", "Central Puget Sound Demographic Profile", target="_blank"),
                                    br(),
                                    tags$a(class = "source_url", href="https://www.psrc.org/displacement-risk-mapping", "Displacement Risk Mapping", target="_blank"),
                                    br(),
                                    tags$a(class = "source_url", href="https://www.psrc.org/opportunity-mapping", "Opportunity Mapping", target="_blank"),
                                    br(),
                                    tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/rtp-appendixb-equityanalysis.pdf", "Regional Transportation Plan Equity Analysis", target="_blank"),
                                    br(),
                                    tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/vision2050equitypaper.pdf", "VISION 2050: Equity Briefing Paper", target="_blank"),
                                    br(),
                                    tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/v2050finalseis-appendixh-equity-march2020.pdf", "VISION 2050 Final SEIS Appendix H: Equity Analysis", target="_blank"),
                                    hr(),
                                    h4("Would you like more information?"),
                                    hr(),
                                    strong(tags$div(class="sidebar_notes","Charles Patton, Ph.D.")),
                                    tags$a(class = "source_url", href="https://www.psrc.org/contact-center/have-question?contact=9626&destination=node/9362&width=75%25&height=75%25&subject=Planning%20for%20Equity", "Email", target="_blank"),
                                    br(),
                                    tags$div(class="sidebar_notes","206-971-3285"),
                                    hr(),
                                    width=3),
                      mainPanel(id="mainpanel",
                        h1("Median Household Income"),
                        "The median household income by race and ethnicity as well as the ratio of those median incomes to that of all households are highlighted in the data on this page.",
                        hr(),
                        h2("Regional"),
                        "In 2019, Asian households had the highest median household income in the region and along with white households, were the only ones in the Seattle-Tacoma-Bellevue MSA to be above the regional average.",
                        br(),
                        fluidRow(column(12,h3("Median Household Income by Race"))),
                        fluidRow(column(12,plotlyOutput("chart_region_income"))),
                        fluidRow(br(),column(12, "place holder for table")),
                        hr(),
                        h2("County"),
                        "The median household income by race and ethnicity ",
                        br(),
                        fluidRow(column(12,h3("Median Household Income by Race"))),
                        fluidRow(column(12,plotlyOutput("chart_county_income"))),
                        br(),
                        
                      ) # End of Main Panel of Median Income
                    ) # End of Sidebar of Median Income
           ),# End of Tab Panel of Median Income
          
           tabPanel("Educational Attainment",
                    sidebarLayout(
                      sidebarPanel(id="sidebar",
                                   div(img(src="psrc-logo.png", width = "100%", height = "100%", style = "padding-top: 5px")),
                                   hr(),
                                   h3("Equity Resources:"),
                                   hr(),
                                   tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/demographicprofile.pdf", "Central Puget Sound Demographic Profile", target="_blank"),
                                   br(),
                                   tags$a(class = "source_url", href="https://www.psrc.org/displacement-risk-mapping", "Displacement Risk Mapping", target="_blank"),
                                   br(),
                                   tags$a(class = "source_url", href="https://www.psrc.org/opportunity-mapping", "Opportunity Mapping", target="_blank"),
                                   br(),
                                   tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/rtp-appendixb-equityanalysis.pdf", "Regional Transportation Plan Equity Analysis", target="_blank"),
                                   br(),
                                   tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/vision2050equitypaper.pdf", "VISION 2050: Equity Briefing Paper", target="_blank"),
                                   br(),
                                   tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/v2050finalseis-appendixh-equity-march2020.pdf", "VISION 2050 Final SEIS Appendix H: Equity Analysis", target="_blank"),
                                   hr(),
                                   h4("Would you like more information?"),
                                   hr(),
                                   strong(tags$div(class="sidebar_notes","Charles Patton, Ph.D.")),
                                   tags$a(class = "source_url", href="https://www.psrc.org/contact-center/have-question?contact=9626&destination=node/9362&width=75%25&height=75%25&subject=Planning%20for%20Equity", "Email", target="_blank"),
                                   br(),
                                   tags$div(class="sidebar_notes","206-971-3285"),
                                   hr(),
                                   width=3),
                      mainPanel(id="mainpanel",
                                h1("Educational Attainment"),
                                "The educational attainment by race and ethnicity are highlighted in the data on this page.",
                                hr(),
                                h2("Regional"),
                                "In 2019, ...",
                                br(),
                                fluidRow(column(12,h3("High School Graduation Rate by Race"))),
                                fluidRow(column(12,plotlyOutput("chart_region_education_hs"))),
                                br(),
                                fluidRow(column(12,h3("College Graduation Rate by Race"))),
                                fluidRow(column(12,plotlyOutput("chart_region_education_bs"))),
                                fluidRow(br(),column(12, "place holder for table")),
                                hr(),
                                h2("County"),
                                "In 2019, ...",
                                br(),
                                fluidRow(column(12,h3("High School Graduation Rate by Race"))),
                                fluidRow(column(12,plotlyOutput("chart_county_education_hs"))),
                                br(),
                                fluidRow(column(12,h3("College Graduation Rate by Race"))),
                                fluidRow(column(12,plotlyOutput("chart_county_education_bs"))),
                                fluidRow(br(),column(12, "place holder for table")),
                                hr(),
                                
                      ) # End of Main Panel of Educational Attainment
                    ) # End of Sidebar of Educational Attainment
           ),# End of Tab Panel of Educational Attainment
           
           tabPanel("Home Ownership",
                    sidebarLayout(
                      sidebarPanel(id="sidebar",
                                   div(img(src="psrc-logo.png", width = "100%", height = "100%", style = "padding-top: 5px")),
                                   hr(),
                                   h3("Equity Resources:"),
                                   hr(),
                                   tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/demographicprofile.pdf", "Central Puget Sound Demographic Profile", target="_blank"),
                                   br(),
                                   tags$a(class = "source_url", href="https://www.psrc.org/displacement-risk-mapping", "Displacement Risk Mapping", target="_blank"),
                                   br(),
                                   tags$a(class = "source_url", href="https://www.psrc.org/opportunity-mapping", "Opportunity Mapping", target="_blank"),
                                   br(),
                                   tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/rtp-appendixb-equityanalysis.pdf", "Regional Transportation Plan Equity Analysis", target="_blank"),
                                   br(),
                                   tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/vision2050equitypaper.pdf", "VISION 2050: Equity Briefing Paper", target="_blank"),
                                   br(),
                                   tags$a(class = "source_url", href="https://www.psrc.org/sites/default/files/v2050finalseis-appendixh-equity-march2020.pdf", "VISION 2050 Final SEIS Appendix H: Equity Analysis", target="_blank"),
                                   hr(),
                                   h4("Would you like more information?"),
                                   hr(),
                                   strong(tags$div(class="sidebar_notes","Charles Patton, Ph.D.")),
                                   tags$a(class = "source_url", href="https://www.psrc.org/contact-center/have-question?contact=9626&destination=node/9362&width=75%25&height=75%25&subject=Planning%20for%20Equity", "Email", target="_blank"),
                                   br(),
                                   tags$div(class="sidebar_notes","206-971-3285"),
                                   hr(),
                                   width=3),
                      mainPanel(id="mainpanel",
                                h1("Home Ownership"),
                                "The percetnage of home ownership by race and ethnicity are highlighted in the data on this page.",
                                hr(),
                                h2("Regional"),
                                "In 2019, ...",
                                br(),
                                fluidRow(column(12,h3("Home Ownership Rate by Race"))),
                                fluidRow(column(12,plotlyOutput("chart_region_homeownership"))),
                                fluidRow(br(),column(12, "place holder for table")),
                                hr(),
                                h2("County"),
                                "In 2019, ...",
                                br(),
                                fluidRow(column(12,h3("Home Ownership Rate by Race"))),
                                fluidRow(column(12,plotlyOutput("chart_county_homeownership"))),
                                fluidRow(br(),column(12, "place holder for table")),
                                hr(),
                      ) # End of Main Panel of Home Ownership
                    ) # End of Sidebar of Home Ownership
           )# End of Tab Panel of Home Ownership          
          )# End of Nav Bar Menu for Economic Data


  ) # End of NavBar Page
) # End of Shiny App
